/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class FuseMount {
  get mountpoint(): string;
  get mounted(): boolean;
  get pending(): number;
  replyEntry(id: number, attr: FuseAttr): void;
  /**
   * Answer a lookup that found nothing. The kernel caches the absence for
   * the entry TTL, so repeated probes for the same missing name stop
   * arriving; an entry invalidation (or expiry) brings them back.
   */
  replyEntryNegative(id: number, ttlMs?: number | undefined | null): void;
  replyAttr(id: number, attr: FuseAttr): void;
  replyData(id: number, data: Buffer): void;
  replyOpen(
    id: number,
    fh: number,
    keepCache?: boolean | undefined | null,
  ): void;
  replyOk(id: number): void;
  /**
   * Adds entries until the kernel's buffer is full; the caller resumes from
   * the offset of the last entry the kernel echoes back.
   */
  replyDirectory(id: number, entries: Array<FuseDirEntry>): void;
  /**
   * The directory reply with attributes per entry, so the kernel skips
   * the follow-up lookups. Returns how many entries the kernel's buffer
   * accepted: the kernel takes a lookup reference for each of those
   * (`.` and `..` excepted), and none for the surplus.
   */
  replyDirectoryPlus(id: number, entries: Array<FuseDirPlusEntry>): number;
  replyError(id: number, code: number): void;
  /** Drop cached attributes (offset -1) or data of an inode. */
  invalInode(ino: bigint, offset: number, len: number): void;
  /** Drop the kernel's cached name (positive or negative) under a directory. */
  invalEntry(parent: bigint, name: string): void;
  unmount(): Promise<unknown>;
}

export interface FuseAttr {
  ino: bigint;
  size: number;
  /** 0 directory, 1 regular file, 2 symlink. */
  kind: number;
  perm: number;
  nlink: number;
  mtimeMs: number;
  uid: number;
  gid: number;
  blksize: number;
  /**
   * Cache TTL for this reply, overriding the mount-wide defaults. Lets
   * synthetic directories (rarely changing, invalidation-pushed) be cached
   * longer than files.
   */
  ttlMs?: number;
}

export interface FuseDirEntry {
  ino: bigint;
  /** Offset the kernel passes back to continue after this entry. */
  offset: number;
  kind: number;
  name: string;
}

/**
 * A readdirplus entry: name plus full attributes, so the kernel skips the
 * per-name lookup round trips that follow a plain readdir.
 */
export interface FuseDirPlusEntry {
  /** Offset the kernel passes back to continue after this entry. */
  offset: number;
  name: string;
  attr: FuseAttr;
}

export interface FuseMountOptions {
  fsName?: string;
  allowOther?: boolean;
  autoUnmount?: boolean;
  entryTtlMs?: number;
  attrTtlMs?: number;
}

/**
 * One kernel request as the JavaScript handler sees it. `id` keys the parked
 * reply; 0 means no reply is expected (`forget`).
 */
export interface FuseRequest {
  id: number;
  op: string;
  /** The node itself, or the parent for name-based operations. */
  ino: bigint;
  name?: string;
  fh?: number;
  offset?: number;
  size?: number;
  nlookup?: number;
  uid: number;
  gid: number;
  pid: number;
}

/** Mount `mountpoint` and start answering the kernel through `handler`. */
export declare function mount(
  mountpoint: string,
  options: FuseMountOptions,
  handler: (arg: FuseRequest) => unknown,
): FuseMount;

/**
 * Lazily detach whatever is mounted at `mountpoint` (a stale mount left by a
 * dead process, typically).
 */
export declare function umountDetach(mountpoint: string): void;
